# pull official base image
FROM node:13.12.0-alpine

# set working directory
WORKDIR /app

ADD . ./app/ticker
# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
#COPY ./ticker/package.json ./
#COPY ./ticker/package-lock.json ./

# add app
WORKDIR /app/ticker

RUN npm install --silent
RUN npm install react-scripts@3.4.1 -g --silent

EXPOSE 3000:3000

# start app
CMD ["npm", "start"]